### PR TITLE
Warning message: commas replaced by semi-colons

### PR DESCRIPTION
**Pull request by LaurentBarbareau**
Consistency with https://github.com/jquery/jquery-migrate/pull/222/commits/cfc0f4ef1028a4d9e423e2ace258a5355b875c3d

### CODE REVIEW

**Comment by mgol** [comment]
Thanks for the PR but let's keep all the related changes in #222; we'd like to land them in one commit anwyay.

**Comment by dmethvin** [comment]
@LaurentBarbareau Just make another commit on your `patch-1` branch over in #222 and push it. When we land it we will squash the two commits. The reason for keeping it in one place is to be sure that the master branch is consistent as often as possible rather than having the work be half-done in two different commits. Thanks for your help, if you need assistance with this just post a question in #222!

**Comment by LaurentBarbareau** [comment]
I understand why you want to keep all in #222 but I don't know how to do.
Can I make it from the GitHub web interface?
thx

**Comment by dmethvin** [comment]
I didn't know the answer before but just found out. :smile_cat: 

Go to the jquery fork in your account and find the `patch-1` branch, it's at https://github.com/LaurentBarbareau/jquery-migrate/tree/patch-1 . Then go to the file you want to edit and click the little pencil icon  Make the change and at the bottom it should have "Commit directly to the patch-1 branch". That will add another commit to your pull request!

**Comment by dmethvin** [comment]
Normally the Github web interface isn't flexible enough, since it isn't possible to create and run additional unit tests that way. For documentation issues like this it is fine though.

**Comment by LaurentBarbareau** [comment]
Thank you.
Done.

**Pull request closed without merging**
