### PR TITLE
Build: enable coveralls repro & allow testing \w building

### PR DESCRIPTION
**Pull request by markelog**
Make you define two module list though :/

### CODE REVIEW

**Comment by markelog** [comment]
@dmethvin - https://coveralls.io/builds/5230460/source?filename=src%2Fmanipulation.js

**Comment by dmethvin** [comment]
I like it! Too bad we need another module list though.

**Comment by markelog** [comment]
At least, although not the same, we are bad everywhere - 
https://github.com/jquery/jquery/blob/8a91f8442f4d31bdd4b43035ee88d40fbb116f64/Gruntfile.js#L132
https://github.com/jquery/jquery/blob/8a91f8442f4d31bdd4b43035ee88d40fbb116f64/test/data/testinit.js#L279

**Comment by dmethvin** [comment]
Yeah I always forget to change it in every place whenever I'm adding a module. :smiley_cat:

**Comment by mgol** [comment]
If only we had a cross-environment module system...

**Pull request closed without merging**
