### PR TITLE
Build: add UMD support

### PR DESCRIPTION
**Pull request by niksy**
This PR implements UMD support as discussed in #98 regarding "Support CJS internally".

### CODE REVIEW

**Comment by dmethvin** [comment]
Awesome, thanks!

**Comment by dmethvin** [comment]
We may want to add `return jQuery` in outro.js so that it will return the modified jQuery when used with CJS. It's going to actually modify its incoming `jQuery` arg, but it seems like using the return value might be more natural. What do you think?

**Comment by niksy** [comment]
@dmethvin yeah, that makes sense! Do you think these change should be applied to `1x-stable` branch, and not only to jQuery v3?

**Comment by dmethvin** [comment]
Yes, I can cherry pick it into that branch as well and do new releases for both.

**Comment by niksy** [comment]
OK, should I squash those 2 commits before merge?

**Comment by dmethvin** [comment]
I can squash them when I land it.

**Comment by mgol** [comment]
Why is `jquery` a dependency and not a peerDependency? This seems wrong as Migrate should be always patching an existing jQuery copy and not provide its own.

**Comment by dmethvin** [comment]
I remember thinking about this at the time, the issue with peerDependencies is that npm3 requires you to install them manually and I didn't wan't to do that. Maybe there is another way out? Perhaps just devDependency, since the Migrate code itself dynamically checks that there is a jQuery core loaded.

**Comment by mgol** [comment]
> I remember thinking about this at the time, the issue with peerDependencies is that npm3 requires you to install them manually and I didn't wan't to do that.

There's no way around that. The purpose of `peerDependencies` is to depend on a package that needs to have one instance and you can't create your own. The correct way to go is to put it both in `devDependencies` and `peerDependencies` (the version range in `peerDependencies` should be more forgiving) and remove from `dependencies`.

**Pull request closed without merging**
