### PR TITLE
Update attributes.js

### PR DESCRIPTION
**Pull request by mattbrundage**
Diction. "May" connotes permission. "Might" connotes a possibility. (http://english.stackexchange.com/questions/7/may-might-whats-the-right-context)

### CODE REVIEW

**Comment by dmethvin** [comment]
Thanks, can you update the docs warning message [here](https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnattrselected-may-use-property-instead-of-attribute) as well?

**Comment by mattbrundage** [comment]
Done.

**Comment by timmywil** [comment]
The second answer on that question is more correct. Might and may can be used interchangeable in the present tense, so this PR isn't necessary.

**Comment by timmywil** [comment]
On the other hand, I like might better.

**Comment by dmethvin** [comment]
Thanks, sorry about the delay!

**Pull request closed without merging**
